<?xml version="1.0"?>
<package format="2">
  <name>sea_surface_segmentation</name>
  <version>0.0.0</version>
  <description>Package that compines eWaRS and depthai_ros to perform segmentation on an Luxonis Oak camera.</description>

  <maintainer email="roland@ccom.unh.edu">Roland Arsenault</maintainer>

  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>camera_info_manager</depend>
  <depend>cv_bridge</depend>
  <depend>depthai</depend>
  <depend>depthai_bridge</depend>
  <depend>image_geometry</depend>
  <depend>nav2_costmap_2d</depend>
  <depend>pluginlib</depend>
  <depend>pcl_conversions</depend>
  <depend>pcl_ros</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>


  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
